### 1. 공지 생성 (createNotice)
POST http://localhost:4000/api/v2/notices
Content-Type: application/json

{
  "title": "공지다 !",
  "content": "첫번째 공지다 이것들아 !",
  "category": "MAINTENANCE",
  "isPinned": false,
  "apartmentId": "d22952ee-f44f-4d2d-84c6-f8b00c9e3d1a",
  "event": {
    "startDate": "2026-01-11T00:00:00Z",
    "endDate": "2026-01-12T00:00:00Z"
  }
}

### 2. 공지 전체 조회 (getAllNotices)
GET http://localhost:4000/api/v2/notices
Content-Type: application/json

### 3. 공지 상세 조회 (getPoll)
GET http://localhost:4000/api/v2/notices/5302543c-c8a5-4c30-98aa-a010bb90d758
Content-Type: application/json

### 4. 공지 수정 (updateNtocie)
PATCH  http://localhost:4000/api/v2/notices/5302543c-c8a5-4c30-98aa-a010bb90d758
Content-Type: application/json

{
  "title": "수정이지롱~",
  "category": "COMMUNITY",
  "isPinned": true,
  "event": {
    "startDate": "2026-01-20T02:13:14.159Z",
    "endDate": "2026-01-20T02:13:14.159Z"
  }
}

### 5. 공지 삭제 (deleteNotice)
DELETE http://localhost:4000/api/v2/notices/5302543c-c8a5-4c30-98aa-a010bb90d758
Content-Type: application/json

### 6. 이벤트 조회 (getEvnets)
GET http://localhost:4000/api/v2/events?apartmentId=d22952ee-f44f-4d2d-84c6-f8b00c9e3d1a&year=2026&month=1
Content-Type: application/json
