### 1.슈퍼 관리자 계정 생셩
POST http://localhost:4000/api/v2/users/super-admins
Content-Type: application/json

{
  "username": "super",
  "email": "super@super.com",
  "contact": "01011112222",
  "name": "손훈석",
  "password": "test1234!"
}

### 2. 관리자 계정 생성
POST http://localhost:4000/api/v2/users/admins
Content-Type: application/json

{
  "username": "admin1",
  "email": "admin1@admin.com",
  "contact": "01012341234",
  "name": "admin",
  "password": "test1234!",
  "adminOf": {
    "name": "갤럭시빌",
    "address": "경기도 용인시 기흥구",
    "description": "자취방",
    "officeNumber": "5",
    "buildingNumberFrom": 1,
    "buildingNumberTo": 2,
    "floorCountPerBuilding": 1,
    "unitCountPerFloor": 3
  }
}

### 3. 관리자 계정 가입 상태 변경 단건. 슈퍼관리자 권한 필요.
PATCH http://localhost:4000/api/v2/users/admins/3fd90df7-325b-456f-a9f4-96bb5cfe5847/join-status
Content-Type: application/json

{
  "joinStatus": "APPROVED"
}

### 4. 주민 계정 생성
POST http://localhost:4000/api/v2/users/residents
Content-Type: application/json

{
  "username": "입주민1",
  "email": "hi@naver.com",
  "contact": "01099998888",
  "name": "주민입니다.",
  "password": "test1234!",
  "resident": {
    "apartmentId": "d22952ee-f44f-4d2d-84c6-f8b00c9e3d1a",
    "building": 1,
    "unit": 1
  }
}
